### ISSUE TITLE
Are you using float64 because of accuracy? Will float32 be faster?

### ISSUE THREAD

**Issue by treeform** [mratsim/trace-of-radiance#6]
I noticed you are using float64 everywhere. Is it because of accuracy? 
Do you think float32 will be faster? Did you do any timing with float64 vs float32?

**Comment by mratsim** [comment]
The tutorial uses float64.

I did a little research and accuracy seems to be important but may be traded off for memory/speed. But it might require more samples per pixels. For example in ETH Zurich courses by Wenzel Jakob, one of the co-author of the Physically-Based rendering book:
- https://github.com/mmp/pbrt-v3
- https://pbrt.org/
- https://cgl.ethz.ch/teaching/cg19/www-nori/index.html
- https://github.com/wjakob/nori

They use Nori as a base which uses float32.

## Regarding speed:

On CPU float32/float64 actually have the same speed at the hardware level: https://software.intel.com/sites/landingpage/IntrinsicsGuide/#techs=SSE2&expand=154,121

![image](https://user-images.githubusercontent.com/22738317/86447111-24590c80-bd15-11ea-9c07-746e877debbf.png)

What matters is how many you can pack per SIMD execution.

In our case, having float32 instead of float64 will accelerate those operations:
https://github.com/mratsim/trace-of-radiance/blob/99f7d85dec857f0efa0c9b0eafd339871599c0e1/trace_of_radiance/primitives/vec3s.nim#L23-L107

Instead of processing 2 coordinates then 1, we process all the 3 in a single SIMD operation for a potential speed-up of 2 on straightforward operations like `add`.
On operations like dot/cross product, the compiler might have to assemble some 1 by 1 and start scheduling independent operations to achieve latency hiding.

For example an optimized vectorized sum reduction that can be used for dot product would look like this in SSE3:
https://github.com/numforge/laser/blob/d1e6ae61/laser/primitives/private/sse3_utils.nim#L8-L18

```Nim
template m128_reduction(op_name, scalar_op, vector_op: untyped) =
  func op_name*(vec: m128): m128 {.inline.}=
    ## Reduce packed packed 4xfloat32
    let shuf = mm_movehdup_ps(vec)
    let sums = vector_op(vec, shuf)
    let shuf2 = mm_movehl_ps(sums, sums)
    result = scalar_op(sums, shuf2) # .mm_cvtss_f32

m128_reduction(sum_ps_sse3, mm_add_ss, mm_add_ps)
m128_reduction(max_ps_sse3, mm_max_ss, mm_max_ps)
m128_reduction(min_ps_sse3, mm_min_ss, mm_min_ps)
```

## When is there a significant difference

There are 2 situations where float32 and float64 will make a significant differences:

1. On GPUs, on consumer GPU float64 is significantly slower than float32, not just 2x but ~32x if I recall correctly.

2. If we change the layout so that we store coordinates contiguously to process multiple Vec3 at once i.e. use

from
```Nim
type
  Vec3 = object
    x, y, z: float32

  Vec3s = seq[Vec3]
```

to

```Nim
type
  Vec3s = object
    x, y, z: seq[float32]
```

In that case, instead of having a ceiling of trying to processing 3 coordinates at once, we can process 8 coordinates at once (AVX) or 16 at once (AVX512)

**Comment by treeform** [comment]
Wow thank you for the detailed repose!
